### ISSUE TITLE
Error running regrading - ag-rerun-grader error

### ISSUE THREAD

**Issue by liamoreilly** [eecs-autograder/autograder-full-stack#12]
We have deployed Autograder Full Stack and it has been running well. A few days ago a staff member attempted to rerun the grading. The percentage was stuck at 0%. The staff member then cancelled the regrading and restarted it several times. It has been left overnight and still the percentage is 0%.

Looking at the docker output I find the following:

```
ag-rerun-grader             | [2021-03-23 17:26:03,993: WARNING/ForkPoolWorker-1] Error in
ag-rerun-grader             | [2021-03-23 17:26:03,993: WARNING/ForkPoolWorker-1] load_submission
ag-rerun-grader             | [2021-03-23 17:26:03,993: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
ag-rerun-grader             | [2021-03-23 17:26:03,993: WARNING/ForkPoolWorker-1] File "/usr/src/app/autograder/utils/retry.py", line 61, in func_with_retry
ag-rerun-grader             |     return func(*args, **kwargs)
ag-rerun-grader             | [2021-03-23 17:26:03,993: WARNING/ForkPoolWorker-1] File "/usr/src/app/autograder/grading_tasks/tasks/rerun_submission.py", line 78, in load_submission
ag-rerun-grader             |     self._rerun_task = ag_models.RerunSubmissionsTask.objects.get(pk=self._rerun_task_pk)
ag-rerun-grader             | [2021-03-23 17:26:03,993: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
ag-rerun-grader             |     return getattr(self.get_queryset(), name)(*args, **kwargs)
ag-rerun-grader             | [2021-03-23 17:26:03,993: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
ag-rerun-grader             |     raise self.model.DoesNotExist(
ag-rerun-grader             | [2021-03-23 17:26:03,993: WARNING/ForkPoolWorker-1] autograder.core.models.rerun_submissions_task.RerunSubmissionsTask.DoesNotExist: RerunSubmissionsTask matching query does not exist.
ag-rerun-grader             | [2021-03-23 17:26:03,993: WARNING/ForkPoolWorker-1] Will try again in
ag-rerun-grader             | [2021-03-23 17:26:03,993: WARNING/ForkPoolWorker-1] 29.516666666666673
ag-rerun-grader             | [2021-03-23 17:26:03,993: WARNING/ForkPoolWorker-1] seconds
```

Deployed is autograder-full-stack on commit e7dc2cb.

I am not at all sure what goes wrong here, if this is a code problem or a data integrity issue. Any ideas would be most welcome. 

Thanks!
Liam

**Comment by james-perretta** [comment]
Hi Liam, I believe this is an issue that I've since patched. If you're able to, please try upgrading to the latest version (tagged as 2021.01.v8), which should fix the issue in two ways: 1) I moved certain lines of code in that endpoint outside of the transaction context manager; 2) I updated the worker logic to drop tasks that throw model.DoesNotExist rather than retrying. So once you update, the task that's at 0% should get picked up fairly quickly.

Now that I think about the code change that I mentioned in 1), I believe the underlying cause may actually be an issue that I've been trying to track down for months (and have recently made progress on). The underlying problem, as far as I can tell, is that uWSGI randomly double-handles requests at the same time in the same process. When one of the threads gets to the end of the request, Django's connection management checks to make sure that a certain setting has been restored. Since the other thread is in the middle of a transaction, that setting has *not* been restored, and so Django closes the database connection. I believe this causes the data loss we're seeing.

The current solution that I'm working on here is to switch from uWSGI to gunicorn, which I'm being very careful about, but I expect my May/June major release to include such a change.

Let me know if this helps...
Thanks!
James

**Comment by james-perretta** [comment]
P.S. See https://github.com/eecs-autograder/autograder-full-stack#upgrading-production-deployments for instructions on upgrading to version 2021.01.v8

**Comment by liamoreilly** [comment]
Wow - Thanks for the super quick response. We have some coursework due in on Friday. So I will try to do this update over the weekend. I will respond here then, hopefully closing this.

**Comment by liamoreilly** [comment]
The upgrade to the latest version fixed the issues. The rerun grader worked its way through processing the missing submissions and then returned to normal. Thanks!
